"""Initialize the flask application."""

from os import environ

from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config["SQLALCHEMY_DATABASE_URI"] = environ["DATABASE_URL"]
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
app.secret_key = b'\x8c\x86\xa6\tRQ\xf3|\xff\xfc\xb2\x8bz\xfe\xe4S' # Generated by os.urandom(16)
db = SQLAlchemy(app)

# pylint: disable=wrong-import-position
from timely import models, views, api
# pylint: enable=wrong-import-position
